### ISSUE TITLE
Recommended icons for status bar?

### ISSUE THREAD

**Issue by Yzrsah** [vikyd/vscode-ext-foldlevel#2]
I attempted to add these fold levels to my status bar, but there didn't seem to be any good octicons or builtin font characters for it.

So I used "＋ ⑶ ⑵ ⑴"

There's some boxy numbered ones but they're super small.

**Comment by vikyd** [comment]
Why add to status bar?

**Comment by Yzrsah** [comment]
I put some things in the status bar to make it easier to remember to use it.
You might forget to use it when there's 500 other hotkeys and things to remember.
For example, I had folding extensions installed for 6 months and I used it 0 times.
I added the Fold Levels to the status bar, and now I use it every day.

**Comment by vikyd** [comment]
vscode-ext-foldlevel only provides command to fold to level, does not care about the icon and UI.

I guess you are using this VSCode extension [vscode-commandbar](https://marketplace.visualstudio.com/items?itemName=gsppvo.vscode-commandbar). You should find the unicode icon from https://unicode-table.com . That's your favorite.

If let me choose one, I may pick this: [ ├ 1   ├ 2   ├ 3  ](https://unicode-table.com/en/#251C)

Here is my `commandbar.json`:


	{
	  "skipTerminateQuickPick": true,
	  "skipSwitchToOutput": false,
	  "skipErrorMessage": true,
	  "commands": [
		{
		  "text": "├ 1",
		  "tooltip": "fold to level 1",
		  "color": "yellow",
		  "command": "vikyd.FoldLevel.level1",
		  "commandType": "palette",
		  "alignment": "left",
		  "skipTerminateQuickPick": false,
		  "priority": 0
		},
		{
		  "text": "├ 2",
		  "tooltip": "fold to level 2",
		  "color": "yellow",
		  "command": "vikyd.FoldLevel.level2",
		  "commandType": "palette",
		  "alignment": "left",
		  "skipTerminateQuickPick": false,
		  "priority": 0
		},
		{
		  "text": "├ 3",
		  "tooltip": "fold to level 3",
		  "color": "yellow",
		  "command": "vikyd.FoldLevel.level3",
		  "commandType": "palette",
		  "alignment": "left",
		  "skipTerminateQuickPick": false,
		  "priority": 0
		}
	  ]
	}

I prefer shortcut instead the commandbar.
