### ISSUE TITLE
Fold on open

### ISSUE THREAD

**Issue by lonix1** [vikyd/vscode-ext-foldlevel#4]
Can I get this somehow to automatically fold on file open?

**Comment by vikyd** [comment]
No and yes.

No: It's not a feature of this extension.

Yes: It's a feature of VSCode.

![foldlevel](https://user-images.githubusercontent.com/2208880/111558245-5fc73880-87c9-11eb-9dcb-71d5cf313216.gif)

**Comment by lonix1** [comment]
Weird doesn't work that way for me. Files don't fold automatically.
